name: Deploy MkDocs Material

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:

permissions:
  contents: write  # Permissions to push to gh-pages
  pages: write     # Permissions for GitHub Pages
  id-token: write  # Permissions for authentication

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the code from the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set Python version for MkDocs

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material 

      - name: Build MkDocs Site
        run: mkdocs build  # Build the MkDocs site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'site'
