name: Deploy MkDocs Material

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  contents: write  # Permissions to push to gh-pages
  pages: write     # Permissions for GitHub Pages
  id-token: write  # Permissions for authentication

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the code from the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set Python version for MkDocs

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # Install MkDocs Material
          pip install mkdocs-plugins  # Install any extra plugins

      - name: Build MkDocs Site
        run: mkdocs build  # Build the MkDocs site

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mkdocs-site
          path: site  # Upload the built site for the deploy job

  deploy:
    needs: build  # Ensure deploy only starts after the build job completes
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: mkdocs-site  # Download the built site artifact

      - name: Deploy MkDocs to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
        run: |
          mkdocs gh-deploy --force  # Deploy to GitHub Pages
